version: "3.3"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c8XAjQCHA?PdVzct
      MYSQL_DATABASE: learning
      MYSQL_USER: mash
      MYSQL_PASSWORD: mash
    ports:
      - "3306:3306"
volumes:
  db_data:
